apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-pv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-pv-app
  template:
    metadata:
      labels:
        app: shared-pv-app
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args: ["while true; do echo $(date) >> /shared-data/log.txt; sleep 5; done"]
        volumeMounts:
        - name: shared-storage
          mountPath: /shared-data
      
      - name: multitool
        image: wbitt/network-multitool:latest
        command: ["/bin/sh", "-c"]
        args: ["tail -f /shared-data/log.txt"]
        volumeMounts:
        - name: shared-storage
          mountPath: /shared-data
      
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: local-pvc
